USE team04;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS batting_stats;
DROP TABLE IF EXISTS pitching_stats;
DROP TABLE IF EXISTS team_match_performance;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS stadiums;
DROP TABLE IF EXISTS teams;

SET FOREIGN_KEY_CHECKS = 1;
